version: '3.8'


# Airflow 공통 설정
x-airflow-common:
  &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.10.5}
  environment:
    &airflow-common-env
    # 1. Executor 설정 (CeleryExecutor 선택)
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    # 메타데이터 저장소
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER:-airflow}:${POSTGRES_PASSWORD:-airflow}@postgres/${POSTGRES_DB:-airflow}
    # 워커가 작업 결과를 저장할 저장소
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER:-airflow}:${POSTGRES_PASSWORD:-airflow}@postgres/${POSTGRES_DB:-airflow}
    # 스케줄러와 워커 사이의 broker 역할을 할 저장소
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    
    # 2. 기본 설정
    # 실행 시 자동 생성되거나 임의의 문자열 필요 (테스트용 공란 가능)
    AIRFLOW__CORE__FERNET_KEY: '' 
    # DAG 생성 시 기본 Pause 상태
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true' 
    # 예제 DAG 로드 안 함 (지저분해짐 방지)
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false' 

    # 3. 웹 서버 관련 설정
    AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT: 300
    AIRFLOW__WEBSERVER__WORKERS: 2
    
    # 3. MinIO 연동 자동 설정 (S3 Connection 미리 주입)
    # 형식: aws://<login>:<password>@?extra__aws__endpoint_url=<endpoint>
    AIRFLOW_CONN_MINIO_S3: "aws://${MINIO_ROOT_USER:-minioadmin}:${MINIO_ROOT_PASSWORD:-minioadmin}@?extra__aws__endpoint_url=http://minio:9000"

  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}:0" # 리눅스/WSL 권한 문제 방지
  depends_on:
    &airflow-common-depends-on
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy
  networks:
    - data-network

services:
  # ==========================================
  # 1. Infra (DB, Cache, Object Storage)
  # ==========================================
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      # 컨테이너 생성 시 최고 관리자 계정 이름과 패스워드 지정
      POSTGRES_USER: ${POSTGRES_USER:-airflow}         
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-airflow} 
      POSTGRES_DB: ${POSTGRES_DB:-airflow}             
    ports:
      - "5432:5432"
    # 데이터 영구 저장을 위한 volumn 연결
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-airflow}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - data-network

  redis: # CeleryExecutor를 위한 메시지 브로커
      image: redis:latest
      container_name: redis
      ports:
        - "6379:6379"
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 30s
        retries: 3
      restart: always
      networks:
        - data-network

  minio:  # S3 호환 스토리지 (DL)
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    container_name: minio
    # 서버 실행 명령: 데이터 디렉토리 지정 및 콘솔 포트 고정
    command: minio server /data --console-address ":9001" --address ":9000"
    environment:
      # MinIO 관리자 ID/PW (S3 Access Key / Secret Key 역할)
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "9000:9000" # API 포트 (Airflow 등 프로그램이 접속)
      - "9001:9001" # 웹 콘솔 포트 (브라우저로 접속)
    volumes:
      - ./minio_data:/data # 데이터 영구 저장
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - data-network

  # ==========================================
  # 2. Airflow Core Components
  # ==========================================
  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 30s
      retries: 5
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-worker: # 실제 작업을 수행하는 Celery Worker
    <<: *airflow-common
    command: celery worker
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 30s
      timeout: 30s
      retries: 5
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-triggerer: # (optional) 비동기 작업/센서 최적화용. worker의 기다리는 작업을 관리해준다
    <<: *airflow-common
    command: triggerer
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-flower: # (optional) Celery Worker, Redis 모니터링용
    <<: *airflow-common
    command: celery flower
    ports:
      - "5555:5555"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5555/"]
      interval: 30s
      timeout: 30s
      retries: 5
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - data-network

  # ==========================================
  # 3. 초기화 (최초 실행 시 DB 생성)
  # ==========================================
  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        if [[ -z "${AIRFLOW_UID}" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\033[0m"
          echo "If you are on Linux/WSL, make sure to set .env file."
          echo
        fi
        # DB 마이그레이션 및 관리자 계정 생성
        airflow db migrate 
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-admin}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-admin}

  
networks:
  data-network:
    driver: bridge